# Generated by Django 2.2.6 on 2021-02-10 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='NO')),
                ('user_id', models.CharField(max_length=25, verbose_name='ID')),
                ('password', models.CharField(max_length=25, verbose_name='PWD')),
                ('name', models.CharField(max_length=25, verbose_name='NAME')),
                ('birthday', models.DateField(max_length=25, verbose_name='B-DAY')),
                ('mail', models.CharField(max_length=25, verbose_name='E-MAIL')),
                ('regist_date', models.CharField(default='2021-02-10', max_length=25, verbose_name='REG_DATE')),
                ('withdrawal_date', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('todo_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='NO')),
                ('content', models.CharField(max_length=255, verbose_name='CONTENT')),
                ('date', models.CharField(default='2021-02-10', max_length=25, verbose_name='DATE')),
                ('is_done', models.BooleanField(default=False, verbose_name='IS_DONE')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.UserInfo', verbose_name='USER_NO')),
            ],
        ),
    ]
