# Generated by Django 2.2.6 on 2021-04-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(default='2021-04-07', max_length=25, verbose_name='DATE'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='regist_date',
            field=models.CharField(default='2021-04-07', max_length=25, verbose_name='REG_DATE'),
        ),
    ]
